# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{serialization_scopes}
  s.version = "0.2.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Dimitrij Denissenko"]
  s.date = %q{2010-08-19}
  s.description = %q{Adds named scopes for ActiveRecord serialization methods (to_xml, to_json)}
  s.email = %q{dimitrij@blacksquaremedia.com}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    ".gitignore",
     "Gemfile",
     "Gemfile.lock",
     "README",
     "Rakefile",
     "VERSION",
     "lib/serialization_scopes.rb",
     "lib/serialization_scopes/matchers.rb",
     "lib/serialization_scopes/matchers/serialize_matcher.rb",
     "rails/init.rb",
     "serialization_scopes.gemspec",
     "spec/helper.rb",
     "spec/serialization_scopes_spec.rb"
  ]
  s.homepage = %q{http://github.com/dim/serialization_scopes}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Named scopes for ActiveRecord serialization methods (to_xml, to_json)}
  s.test_files = [
    "spec/helper.rb",
     "spec/serialization_scopes_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activerecord>, ["> 2.5.0"])
    else
      s.add_dependency(%q<activerecord>, ["> 2.5.0"])
    end
  else
    s.add_dependency(%q<activerecord>, ["> 2.5.0"])
  end
end

